name: Deploy blocklist

on:
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        repository: phantom-labs/blocklist
        path: './blocklist'

    - uses: actions/checkout@v3
      with:
        path: './automation'
    
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: './blocklist/yarn.lock'
        
    - run: npm install
      working-directory: './blocklist'
      
    - run: npm run build
      working-directory: './blocklist'
      
    - run: cp ./blocklist/{blocklist,blocklist-full,content-hash}.json ./automation/dist
    
#     - run: git status
#       working-directory: './automation'

    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      working-directory: './automation'
      
    - name: commit
      run: |
        git add .
        git commit -m "Build blocklist"
        git push origin master
      working-directory: './automation'
