name: Deploy blocklist

on:
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        repository: solflare-wallet/blocklist
        path: './blocklist'

    - uses: actions/checkout@v3
      with:
        path: './automation'
    
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: './blocklist/yarn.lock'
        
    - run: npm install
      working-directory: './blocklist'
      
    - run: npm run build
      working-directory: './blocklist'
      
    - run: cp ./blocklist/{blocklist,content-hash}.json ./automation/dist
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: './automation'
